### ISSUE TITLE
Head control broken

### ISSUE THREAD

**Issue by friendlygiant2** [explorer-01-2018/beinghuman#2]
### Steps to reproduce
Put child in face-down position. Will not move head and suffocate

 _(ignore timestamp, this is from 26 feb)_

**Comment by explorer-01-2018** [comment]
Yes, this is a serious bug that needs immediate attention. Complete control is not possible with current hardware. But with the patches for milestone 0.1 I included the following workaround: 

1. Can detect this situation
2. will lift head for about 10 seconds
3. will issue audible warning on stderr
4. will turn head 90 degrees in random direction and put it down. 
_(ignore timestamp, this is from 26 feb)_

**Comment by friendlygiant2** [comment]
works for me. 
_(ignore timestamp, this is from 26 feb)_
